_target_: mattergen.common.data.datamodule.CrystDataModule
_recursive_: true
properties:
  - force_rms
  # Supported properties:
  # - dft_bulk_modulus
  # - dft_band_gap
  # - dft_mag_density
  # - ml_bulk_modulus
  # - hhi_score
  # - space_group
  # - energy_above_hull
  # - force_rms

dataset_transforms: 
  - _target_: mattergen.common.data.dataset_transform.filter_sparse_properties
    _partial_: true

transforms:
- _target_: mattergen.common.data.transform.symmetrize_lattice
  _partial_: true
- _target_: mattergen.common.data.transform.set_chemical_system_string
  _partial_: true

average_density: 0.0500000 # atoms/Angstrom**3
root_dir: /lustre/orion/world-shared/lrn070/jyc/frontier/dataset_sc26_restripe/OMat24-v2.bp # this is big omat
#root_dir: /lustre/orion/lrn070/proj-shared/patxi/adios/data/miniOMat24-forces/miniOMat24-forces-85k.bp # this is the small one

train_dataset:
  _target_: mattergen.common.data.dataset.CrystalDataset.from_adios_file_hydragnn
  split: trainset
  data_path: ${data_module.root_dir}
  properties: ${data_module.properties}
  transforms: ${data_module.transforms}
  keys: ['pos','cell','atomic_numbers','forces']
  dataset_transforms: ${data_module.dataset_transforms}

val_dataset:
  _target_: mattergen.common.data.dataset.CrystalDataset.from_adios_file_hydragnn
  split: valset
  data_path: ${data_module.root_dir}
  properties: ${data_module.properties}
  transforms: ${data_module.transforms}
  keys: ['pos','cell','atomic_numbers','forces']
  dataset_transforms: ${data_module.dataset_transforms}

num_workers:
  train: 0
  val: 0

batch_size:
  # total batch size of 512, adjust for number of devices, nodes, and gradient accumulation
  # train:  ${eval:'((512//1) // ${trainer.accumulate_grad_batches}) // (${trainer.devices} * ${trainer.num_nodes})'}
  # val: ${eval:'((128//1) // ${trainer.accumulate_grad_batches}) // (${trainer.devices} * ${trainer.num_nodes})'}
  train:  ${eval:'(512//8)'}
  val: ${eval:'(512//8)'}

max_epochs: 10000