_target_: mattergen.diffusion.model_module.DiffusionModelModule
optimizer_partial:
  lr: 1e-4
  _target_: torch.optim.Adam
  _partial_: true
scheduler_partials:
  - scheduler:
      _target_: mattergen.diffusion.training_components.get_warmup_piecewise_constant_lr_scheduler
      warmup_iters: 1000
      start_factor: 0.01
      end_factor: 1.0
      step_boundaries: [1000, 2500, 5000, 10000]
      factors: [1.0, 0.5, 0.1, 0.05, 0.01]
      _partial_: true
    interval: step
    frequency: 1
